### ISSUE TITLE
parent command [cmdx] has duplicated subcommand name or alias:

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/cmdx#1032]
Version: 1.7.5

```console
$ cmdx -v
cmdx version 1.7.5 (a7711e90e767e8f74db734a54aa50ba83142f674)
```

```console
$ cmdx help
parent command [cmdx] has duplicated subcommand name or alias:
```

## Note

- https://github.com/quay/clair-action/issues/122

**Comment by suzuki-shunsuke** [comment]
- https://github.com/urfave/cli/pull/1805

**Comment by suzuki-shunsuke** [comment]
I couldn't reproduce the issue using the following config.

```yaml
---
tasks:
- name: hello
  description: hello task
  script: echo hello
```

```console
$ cmdx hello
+ echo hello
hello
```

**Comment by suzuki-shunsuke** [comment]
I could reproduce the issue.

```yaml
tasks:
- name: foo
  script: echo foo
- name: bar
  script: echo bar
```

```console
$ cmdx foo 
parent command [cmdx] has duplicated subcommand name or alias: 
```

```console
$ cmdx bar
parent command [cmdx] has duplicated subcommand name or alias:
```

**Comment by suzuki-shunsuke** [comment]
I couldn't reproduce the issue.

```yaml
tasks:
- name: foo
  script: echo foo
  short: f
- name: bar
  script: echo bar
```

I guess empty command aliases causes conflicts.
