### ISSUE TITLE
`duplicated subcommand name or alias` still happens in 1.7.6 with sub tasks

### ISSUE THREAD

**Issue by yudai-nkt** [suzuki-shunsuke/cmdx#1045]
When cmdx defines several tasks that have sub tasks, an error reported in #1032 is raised:

```yaml
tasks:
  - name: foo
    tasks:
      - name: bar
        script: ":"
  - name: baz
    tasks:
      - name: qux
        script: ":"
```

```console
$ cmdx -v
cmdx version 1.7.6 (29bca03f2177da84d24d1146fba5a8ce4c0ec9fb)
$ cmdx help
parent command [cmdx] has duplicated subcommand name or alias:
```

If either task has a script, this doesn't happen.

```yaml
tasks:
  - name: foo
    tasks:
      - name: bar
        script: ":"
  - name: baz
    script: ":"
```

```console
$ cmdx -v
cmdx version 1.7.6 (29bca03f2177da84d24d1146fba5a8ce4c0ec9fb)
$ cmdx help
NAME:
   cmdx - task runner

USAGE:
   cmdx [global options] command [command options]

VERSION:
   1.7.6 (29bca03f2177da84d24d1146fba5a8ce4c0ec9fb)

AUTHOR:
   Shunsuke Suzuki

COMMANDS:
   foo,
   baz
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --config value, -c value       configuration file path [$CMDX_CONFIG_PATH]
   --name value, -n value         configuration file name. The configuration file is searched from the current directory to the root directory recursively
   --working-dir value, -w value  The working directory path. By default, the task is run on the directory where the configuration file is found [$CMDX_WORKING_DIR]
   --init, -i                     create the configuration file (default: false)
   --list, -l                     list tasks (default: false)
   --quiet, -q                    don't output the executed command (default: false)
   --dry-run, -d                  output the script but don't run it actually (default: false)
   --help, -h                     show help
   --version, -v                  print the version
```
