### ISSUE TITLE
binding variables to environment variables

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/cmdx#26]
```yaml  
bind_env:
  enabled: true
  prefix: FOO
  suffix: BAR
```
