### ISSUE TITLE
Require.exec with aqua

### ISSUE THREAD

**Issue by gedw99** [suzuki-shunsuke/cmdx#415]
Would be cool if the aqua system was used so that if a binary is not there , then aqua gets it for you and uses aqua proxy to run it .

might be best to call it aqua.require.exec so the existing function is not broken ?

**Comment by suzuki-shunsuke** [comment]
Hmm. I think cmdx should be independent of aqua.
Of course, you can use cmdx combined with aqua.
You can just manage tools with aqua and run them via cmdx.

I'm sorry if I'm misunderstanding your proposal.

**Comment by suzuki-shunsuke** [comment]
> You can just manage tools with aqua and run them via cmdx.

e.g.

cmdx.yaml

```yaml
- name: lint
  short: l
  description: lint the go code
  usage: lint the go code
  require:
    exec:
    - golangci-lint
  script: golangci-lint run
```

aqua.yaml

```yaml
registries:
  - type: standard
    ref: v3.146.0
packages:
- name: golangci/golangci-lint@v1.51.2
```
