### ISSUE TITLE
fzf isn't woking in the script

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/cmdx#52]
Maybe [Songmu/timeout](https://github.com/Songmu/timeout) is related.

```yaml
# .cmdx.yaml
tasks:
- name: fzf
  script: "ls | fzf"
```

```console
$ cmdx simple
+ ls | fzf
```

```console
$ cmdx simple
+ ls | fzf
^CFailed to read /dev/tty
the command is canceled
```
