### ISSUE TITLE
Propagate exit code properly

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/cmdx#81]
```yaml
# .cmdx.yaml
- name: false
  script: exit 5
```

```
$ cmdx false
+ exit 5
exit status 5

$ echo $?
1
```
